//! Emit a `NOPASSWD:NOSETENV` sudoers fragment for the daemon.
//!
//! Modeled on the pattern Lima uses for `socket_vmnet` (see
//! `pkg/networks/sudoers.go` in lima-vm/lima): the fragment whitelists
//! a single, fully-specified `usbipd daemon ...` invocation as root
//! for members of a chosen group, so the user can then run
//!
//!     sudo usbipd daemon --listen ... --allow ...
//!
//! passwordlessly. The rule is intentionally narrow — it pins the
//! absolute path of the running binary and the exact argument list —
//! so a typo in either the rule or the invocation fails closed.
//!
//! Why root at all? macOS requires elevated privileges to claim
//! exclusive access to a USB interface that is already bound to a
//! kernel driver (e.g. `IOUSBMassStorageClass` for mass-storage
//! devices). Without it `nusb` fails the URBs with
//! `0xe00002c5 (kIOReturnExclusiveAccess)` even after the import
//! handshake succeeds.

use std::fmt::Write as _;
use std::path::Path;

/// Inputs to [`render`]. All strings come from CLI args and are
/// validated (no whitespace, no sudoers metacharacters) before
/// rendering so the output never needs quoting — `sudoers(5)`
/// command specifications cannot quote arguments.
pub struct Spec<'a> {
    /// Unix group whose members get the NOPASSWD rule (e.g. `admin`).
    pub group: &'a str,
    /// Absolute path to the `usbipd` binary the rule will whitelist.
    /// Must match the path the user will actually invoke via sudo.
    pub binary: &'a Path,
    /// The full argument vector that will follow `usbipd` on the
    /// command line (e.g. `["daemon", "--listen", "127.0.0.1:3240",
    /// "--allow", "0781:5530"]`). Must be non-empty.
    pub args: &'a [&'a str],
}

/// We accept only an allowlist of characters that are safe to put
/// verbatim in a `sudoers(5)` `Cmnd` line. This covers everything
/// real `usbipd daemon` invocations need (paths, hex IDs,
/// `host:port`, `--long-flag`, `--key=value`) while rejecting the
/// whole zoo of sudoers/shell metacharacters (`;`, `,`, `#`, `\`,
/// `*`, `?`, `[`, `]`, `&`, `|`, `<`, `>`, `$`, `` ` ``, quotes,
/// whitespace, …). Whitespace inside an arg can't be expressed at
/// all (sudoers splits on whitespace and we can't quote), so it's
/// rejected too.
fn invalid_chars(s: &str) -> Option<char> {
    s.chars().find(|c| !is_safe_char(*c))
}

fn is_safe_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '.' | '/' | ':' | '=' | '-' | '_' | '+' | '@' | '%')
}

/// Backslash-escape the characters `sudoers(5)` treats as word
/// terminators (`: , = ! ( ) \`). This lets us put e.g.
/// `127.0.0.1:3240` and `0781:5530` directly in the Cmnd line
/// instead of having `:` parsed as a `User_Spec` separator.
fn escape_sudoers(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(c, ':' | ',' | '=' | '!' | '(' | ')' | '\\') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// Render the fragment, or return a human-readable error if the spec
/// can't be expressed safely.
pub fn render(spec: &Spec<'_>) -> Result<String, String> {
    if spec.group.is_empty() {
        return Err("group must not be empty".into());
    }
    if let Some(c) = invalid_chars(spec.group) {
        return Err(format!(
            "group {:?} contains invalid character {c:?}",
            spec.group
        ));
    }
    if !spec.binary.is_absolute() {
        return Err(format!(
            "binary path {:?} must be absolute (sudoers ignores PATH lookup)",
            spec.binary.display()
        ));
    }
    let binary = spec
        .binary
        .to_str()
        .ok_or_else(|| format!("binary path {:?} is not valid UTF-8", spec.binary.display()))?;
    if let Some(c) = invalid_chars(binary) {
        return Err(format!(
            "binary path {binary:?} contains character {c:?} that cannot appear in a sudoers Cmnd"
        ));
    }
    if spec.args.is_empty() {
        return Err("args must not be empty (need at least a subcommand)".into());
    }
    for a in spec.args {
        if a.is_empty() {
            return Err("empty argument is not representable in sudoers".into());
        }
        if let Some(c) = invalid_chars(a) {
            return Err(format!(
                "argument {a:?} contains character {c:?} that cannot appear in a sudoers Cmnd"
            ));
        }
    }

    let mut out = String::new();
    writeln!(
        out,
        "# Generated by `usbipd sudoers` — do not edit by hand."
    )
    .unwrap();
    writeln!(
        out,
        "# Install with:  usbipd sudoers ... | sudo tee /etc/sudoers.d/usbipd"
    )
    .unwrap();
    writeln!(
        out,
        "# Re-run whenever the binary path or daemon arguments change."
    )
    .unwrap();
    writeln!(out).unwrap();
    write!(
        out,
        "%{group} ALL=(root:wheel) NOPASSWD:NOSETENV: {binary}",
        group = spec.group,
        binary = escape_sudoers(binary),
    )
    .unwrap();
    for a in spec.args {
        write!(out, " {}", escape_sudoers(a)).unwrap();
    }
    writeln!(out).unwrap();
    Ok(out)
}

/// Convenience: best-effort guess at the absolute path of the
/// currently-running executable. Falls back to the argv\[0\] path if
/// `current_exe` fails. The result is what users would naturally
/// type to run the daemon, so it's the correct path to bake into
/// the sudoers rule.
pub fn self_path() -> std::path::PathBuf {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.canonicalize().ok())
        .unwrap_or_else(|| {
            std::env::args_os().next().map_or_else(
                || std::path::PathBuf::from("usbipd"),
                std::path::PathBuf::from,
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn ok_spec() -> (PathBuf, Vec<String>) {
        (
            PathBuf::from("/opt/homebrew/bin/usbipd"),
            vec![
                "daemon".into(),
                "--listen".into(),
                "127.0.0.1:3240".into(),
                "--allow".into(),
                "0781:5530".into(),
            ],
        )
    }

    #[test]
    fn renders_expected_fragment() {
        let (bin, args) = ok_spec();
        let args: Vec<&str> = args.iter().map(String::as_str).collect();
        let s = render(&Spec {
            group: "admin",
            binary: &bin,
            args: &args,
        })
        .unwrap();
        assert!(s.contains("%admin ALL=(root:wheel) NOPASSWD:NOSETENV: "));
        // Colons in args/path must be backslash-escaped so the sudoers
        // parser doesn't read them as User_Spec separators.
        assert!(
            s.contains(
                "/opt/homebrew/bin/usbipd daemon --listen 127.0.0.1\\:3240 --allow 0781\\:5530"
            ),
            "got: {s}"
        );
        // Must end with a single trailing newline so concatenation
        // into /etc/sudoers.d/usbipd is well-formed.
        assert!(s.ends_with('\n'));
    }

    #[test]
    fn rejects_relative_binary() {
        let bin = PathBuf::from("usbipd");
        let err = render(&Spec {
            group: "admin",
            binary: &bin,
            args: &["daemon"],
        })
        .unwrap_err();
        assert!(err.contains("absolute"), "got: {err}");
    }

    #[test]
    fn rejects_metacharacters_in_args() {
        let bin = PathBuf::from("/usr/local/bin/usbipd");
        for bad in [
            "dae mon",
            "daemon\n",
            "daemon;rm",
            "daemon*",
            "daemon\\x",
            "a,b",
            "da#emon",
            "da&emon",
            "da|emon",
            "da>emon",
            "da$emon",
            "da`emon",
            "da'emon",
            "da\"emon",
            "da?emon",
            "da[emon",
            "da{emon",
        ] {
            let err = render(&Spec {
                group: "admin",
                binary: &bin,
                args: &[bad],
            })
            .unwrap_err();
            assert!(
                err.contains("character"),
                "expected character-rejection error for {bad:?}, got: {err}"
            );
        }
    }

    #[test]
    fn accepts_realistic_daemon_args() {
        let bin = PathBuf::from("/opt/homebrew/bin/usbipd");
        // Every char class that real daemon invocations use.
        let args = [
            "daemon",
            "--listen",
            "127.0.0.1:3240",
            "--socket",
            "/var/run/usbipd.sock",
            "--allow",
            "0781:5530",
            "--key=value",
            "--allow-public",
        ];
        render(&Spec {
            group: "admin",
            binary: &bin,
            args: &args,
        })
        .unwrap();
    }

    #[test]
    fn rejects_empty_inputs() {
        let bin = PathBuf::from("/usr/local/bin/usbipd");
        assert!(
            render(&Spec {
                group: "",
                binary: &bin,
                args: &["daemon"]
            })
            .is_err()
        );
        assert!(
            render(&Spec {
                group: "admin",
                binary: &bin,
                args: &[]
            })
            .is_err()
        );
        assert!(
            render(&Spec {
                group: "admin",
                binary: &bin,
                args: &[""]
            })
            .is_err()
        );
    }

    #[test]
    fn rejects_metacharacters_in_group_and_binary() {
        let bin_bad = PathBuf::from("/usr/local/bin/usb pd");
        assert!(
            render(&Spec {
                group: "admin",
                binary: &bin_bad,
                args: &["daemon"],
            })
            .is_err()
        );
        let bin_ok = PathBuf::from("/usr/local/bin/usbipd");
        assert!(
            render(&Spec {
                group: "ad min",
                binary: &bin_ok,
                args: &["daemon"],
            })
            .is_err()
        );
    }
}
